### ISSUE TITLE
Cannot serialize BigInt

### ISSUE THREAD

**Issue by ArvidWedtstein** [ArvidWedtstein/ArkDashboard#87]
api |
api | TypeError: Do not know how to serialize a BigInt
api |     at stringify (<anonymous>)
api |     at stringify (C:\Users\arvid.wedtstein\Documents\TS\ArkDashboard\node_modules\core-js-pure\es\json\stringify.js:10:10)
api |     at C:\Users\arvid.wedtstein\Documents\TS\ArkDashboard\node_modules\@redwoodjs\graphql-server\dist\plugins\useRedwoodOpenTelemetry.js:61:71
api |     at field.resolve (C:\Users\arvid.wedtstein\Documents\TS\ArkDashboard\node_modules\@envelop\on-resolve\cjs\index.js:21:56)
api |     at executeField (C:\Users\arvid.wedtstein\Documents\TS\ArkDashboard\node_modules\@graphql-tools\executor\cjs\execution\execute.js:301:24)
api |     at executeFields (C:\Users\arvid.wedtstein\Documents\TS\ArkDashboard\node_modules\@graphql-tools\executor\cjs\execution\execute.js:248:28)
api |     at executeOperation (C:\Users\arvid.wedtstein\Documents\TS\ArkDashboard\node_modules\@graphql-tools\executor\cjs\execution\execute.js:212:18)
api |     at C:\Users\arvid.wedtstein\Documents\TS\ArkDashboard\node_modules\@graphql-tools\executor\cjs\execution\execute.js:66:56
api |     at ValueOrPromise (C:\Users\arvid.wedtstein\Documents\TS\ArkDashboard\node_modules\value-or-promise\src\ValueOrPromise.ts:35:15)
api |     at executeImpl (C:\Users\arvid.wedtstein\Documents\TS\ArkDashboard\node_modules\@graphql-tools\executor\cjs\execution\execute.js:66:12)

**Comment by ArvidWedtstein** [comment]
![Image](https://github.com/ArvidWedtstein/ArkDashboard/assets/71834553/0e397f45-bede-404d-940f-8bfd045ada7f)

**Comment by ArvidWedtstein** [comment]
Kinda fixed by converting BigInt to string.. 

![Image](https://github.com/ArvidWedtstein/ArkDashboard/assets/71834553/01e5c12a-452c-450c-9d35-c8fc8687d5d8)
